#!/bin/sh
#
# Print the current Ruby stable version.
#
# Example:
#
#    $ ruby-stable-version
#    2.3.1
#
# This implementation has three steps:
#
#   * Fetch the Ruby website download page
#   * Search the HTML to match a link to a download file,
#   * Extract the version string, such as "2.3.1".
#
# This implementation intentionally uses just shell tools,
# because we want the script to be as portable as possible.
#
# ## Tracking
#
# Command: ruby-stable-version
# Version: 2.0.0
# Created: 2014-12-06
# Updated: 2016-09-02
# License: BSD, MIT, GPL
# Contact: Joel Parker Henderson (joel@joelparkerhenderson.com)
##
set -euf
curl --silent --location https://www.ruby-lang.org/en/downloads/ |
sed --silent '/.*ruby-\(.*\).tar.gz.*/{s//\1/p;q}'
